# Generated by Django 5.1.2 on 2024-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roommember_insession_alter_roommember_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommember',
            options={'ordering': ['name'], 'verbose_name': 'Room Member', 'verbose_name_plural': 'Room Members'},
        ),
        migrations.AlterField(
            model_name='roommember',
            name='insession',
            field=models.BooleanField(default=True, verbose_name='Is in Session'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Member Name'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.CharField(max_length=200, verbose_name='Room Name'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.CharField(max_length=1000, verbose_name='User ID'),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('uid', 'room_name')},
        ),
    ]
